# Generated by Django 5.0.7 on 2024-07-11 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 11, 48, 55, 136911, tzinfo=datetime.timezone.utc)),
        ),
    ]
