# Generated by Django 5.0.7 on 2024-07-11 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 11, 51, 16, 477298, tzinfo=datetime.timezone.utc)),
        ),
    ]
